name: PSBX
favicon: null
layout_spectrum: 0.191046052146703
typography_spectrum: 0.12353279651142657
title: Welcome to Per Se Brand Experience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1323554499540478
  lightness: 0.5525428776163608
  saturation: 0.5274214441888034
  rhythmicContrast: 0.7005274097900838
purpose: []
