name: PSBX
favicon: null
layout_spectrum: 0.32659
typography_spectrum: 0.86416
title: Welcome to Per Se Brand Experience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fedbc8'
    - '#503232'
    - '#958a76'
    - '#a85f4e'
    - '#f99480'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
