name: PSBX
favicon: null
layout_spectrum: 0.20425
typography_spectrum: 0.91067
title: Welcome to Per Se Brand Experience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5d5d5d'
    - '#000000'
    - '#404040'
    - '#333333'
    - '#666666'
  brandStrength: 0.125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
